export const images = {
  ovalImg: require("./images/ovalImg.jpg"),
  largeImg: require("./images/largeImg.jpg"),
  circleImg: require("./images/circleImg.jpg"),
  slide1: require("./images/slide1.png"),
  slide2: require("./images/slide2.png"),
  slide3: require("./images/slide3.png"),
  apple: require("./images/apple.png"),
  facebook: require("./images/facebook.png"),
  google: require("./images/google.png"),
  imgPick: require("./images/imgPick.png"),
  edit: require("./images/edit.png"),
  blurhash: require("./images/blurhash.png"),
  home: require("./images/home.png"),
  homeo: require("./images/home-o.png"),
  shop: require("./images/shop.png"),
  shopo: require("./images/shop-o.png"),
  heart: require("./images/heart.png"),
  hearto: require("./images/heart-o.png"),
  chat: require("./images/chat.png"),
  chato: require("./images/chat-o.png"),
  profile: require("./images/profile.png"),
  profileo: require("./images/profile-o.png"),
  banner1: require("./images/banner1.png"),
  tshirt: require("./images/tshirt.png"),
  pant: require("./images/pant.png"),
  dress: require("./images/dress.png"),
  jacket: require("./images/jacket.png"),
};

export const fonts = {
  "Montserrat-Regular": require("./fonts/Montserrat-Regular.ttf"),
  "Montserrat-Medium": require("./fonts/Montserrat-Medium.ttf"),
  "Montserrat-SemiBold": require("./fonts/Montserrat-SemiBold.ttf"),
  "Montserrat-Bold": require("./fonts/Montserrat-Bold.ttf"),
};
